<?php

namespace HomeBundle\Repository;

/**
 * DevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisRepository extends \Doctrine\ORM\EntityRepository
{
    
   public function findAllDevisPaginate($search, $page, $perpage)
   {
       $query = $this->_em->createQueryBuilder('d');
       $query->select('d');
       $query->from('HomeBundle:Devis', 'd')
             ->leftJoin('d.project', 'p');
       if ($search != null) {
           $query->andWhere(
               $query->expr()->orX(
                   $query->expr()->like('d.dateofBegining', ':search')
               )
           )->setParameter('search', "%" . $search . "%");
       }
       $query->orderBy('d.dateofBegining', 'desc')
           ->setMaxResults($perpage)
           ->setFirstResult(($page - 1) * $perpage);

       return $query->getQuery()
           ->getResult();
   }
  
   public function countAllDevis($search)
   {
       $query = $this
           ->createQueryBuilder('d')
           ->select('count(d)  ');
       if ($search != null) {
           $query->andWhere(
               $query->expr()->orX(
                   $query->expr()->like('d.dateofBegining', ':search')
               )
           )->setParameter('search', "%" . $search . "%");
       }
       $query->orderBy('d.dateofBegining', 'asc');
       return $query->getQuery()
           ->getSingleScalarResult();
   }

}
