<?php

namespace HomeBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

   public function findAllProjectPaginate($search, $page, $perpage)
   {
       $query = $this->_em->createQueryBuilder('po');
       $query->select('po');
       $query->from('HomeBundle:Project', 'po');
       if ($search != null) {
           $query->andWhere(
               $query->expr()->orX(
                   $query->expr()->like('po.projectName', ':search')
               )
           )->setParameter('search', "%" . $search . "%");
       }
       $query->orderBy('po.projectName', 'desc')
           ->setMaxResults($perpage)
           ->setFirstResult(($page - 1) * $perpage);

       return $query->getQuery()
           ->getResult();
   }
  
   public function findAllProjectRevisePaginate($search, $page, $perpage)
   {
       $query = $this->_em->createQueryBuilder('po');
       $query->select('po');
       $query->from('HomeBundle:Devis', 'po')
             ->leftjoin('po.project', 'd')
             ->orderBy('po.dateofStart', 'ASC');
       if ($search != null) {
           $query->andWhere(
               $query->expr()->orX(
                   $query->expr()->like('d.projectName', ':search')
               )
           )->setParameter('search', "%" . $search . "%");
       }
       $query->orderBy('d.projectName', 'desc')
           ->setMaxResults($perpage)
           ->setFirstResult(($page - 1) * $perpage);

       return $query->getQuery()
           ->getResult();
   }

   public function countAllProject($search)
   {
       $query = $this
           ->createQueryBuilder('p')
           ->select('count(p)  ');
       if ($search != null) {
           $query->andWhere(
               $query->expr()->orX(
                   $query->expr()->like('p.projectName', ':search')
               )
           )->setParameter('search', "%" . $search . "%");
       }
       $query->orderBy('p.projectName', 'asc');
       return $query->getQuery()
           ->getSingleScalarResult();
   }

}
